# Generated by Django 4.1.2 on 2023-04-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='materials',
            new_name='material',
        ),
        migrations.AlterField(
            model_name='task',
            name='age',
            field=models.CharField(max_length=100),
        ),
    ]
